package com.bajiezu.cloud.product.service.app.impl;

import cn.hutool.core.collection.CollectionUtil;
import com.bajiezu.cloud.common.web.pojo.PageResult;
import com.bajiezu.cloud.product.controller.vo.app.request.*;
import com.bajiezu.cloud.product.controller.vo.app.response.*;
import com.bajiezu.cloud.product.dal.entity.*;
import com.bajiezu.cloud.product.dal.mapper.*;
import com.bajiezu.cloud.product.enums.ApproveStatusEnum;
import com.bajiezu.cloud.product.enums.ShelvesStatusEnum;
import com.bajiezu.cloud.product.service.app.AppProductQueryService;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import jakarta.annotation.Resource;
import org.apache.commons.lang3.StringUtils;
import org.springframework.stereotype.Service;

import java.util.*;
import java.util.stream.Collectors;

@Service
public class AppProductQueryServiceImpl implements AppProductQueryService {
@Resource private MarketingProductSpuMapper spuMapper; @Resource private MarketingProductSkuMapper skuMapper; @Resource private MarketingProductSkuPropertyValueMapper skuPropertyValueMapper; @Resource private MarketingProductSpuPropertyValueMapper spuPropertyValueMapper; @Resource private ProductPropertyMapper productPropertyMapper; @Resource private ProductPropertyValueMapper productPropertyValueMapper; @Resource private ValueAddedMapper valueAddedMapper;
public PageResult<AppProductSpuPageRespVO> spuPage(AppProductSpuPageReqVO req){LambdaQueryWrapper<MarketingProductSpu> w=baseSpu(); if(StringUtils.isNotBlank(req.getKeyword()))w.like(MarketingProductSpu::getName,req.getKeyword()); long count=spuMapper.selectCount(w); w.orderByDesc(MarketingProductSpu::getCreateTime).last("limit "+((req.getPageNo()-1)*req.getPageSize())+","+req.getPageSize()); List<MarketingProductSpu> spus=spuMapper.selectList(w); if(CollectionUtil.isEmpty(spus))return PageResult.empty(); List<AppProductSpuPageRespVO> list=new ArrayList<>(); for(MarketingProductSpu s:spus){List<MarketingProductSku> skus=saleableSkusBySpu(s.getId()); if(CollectionUtil.isEmpty(skus))continue; MarketingProductSku d=skus.get(0); AppProductSpuPageRespVO vo=new AppProductSpuPageRespVO(); vo.setSpuId(s.getId()); vo.setName(s.getName()); vo.setMainPicUrl(splitFirst(s.getMainPicUrls())); vo.setDefaultSkuId(d.getId()); vo.setPriceText(d.getDailyRent()==null?null:"¥"+d.getDailyRent()+"/天"); vo.setStockStatus(d.getStock()!=null&&d.getStock()>0?1:0); vo.setShopButtonText("去下单"); list.add(vo);} return new PageResult<>(list,count);} 
public AppProductSpuDetailRespVO spuDetail(AppProductSpuDetailReqVO req){MarketingProductSpu spu=spuMapper.selectOne(baseSpu().eq(MarketingProductSpu::getId,req.getSpuId())); if(spu==null)return null; List<MarketingProductSku> skus=saleableSkusBySpu(spu.getId()); if(CollectionUtil.isEmpty(skus)) return null; MarketingProductSku d=skus.get(0); AppProductSpuDetailRespVO r=new AppProductSpuDetailRespVO(); r.setSpuId(spu.getId()); r.setName(spu.getName()); r.setCondition(spu.getProductCondition()); r.setMainPicUrls(split(spu.getMainPicUrls())); r.setCarouselPicUrls(split(spu.getCarouselPicUrls())); r.setVideoUrls(split(spu.getVideoUrls())); r.setDetailPicUrls(split(spu.getDetailPicUrls())); r.setDefaultSkuId(d.getId()); r.setDailyRent(d.getDailyRent()); r.setOfficialPrice(d.getOfficialPrice()); r.setStrikethroughPrice(d.getStrikethroughPrice()); r.setProperties(buildSkuProps(d.getId())); if(StringUtils.isNotBlank(spu.getValueAddedIds())){List<Long> ids=Arrays.stream(spu.getValueAddedIds().split(",")).map(Long::valueOf).toList(); List<ValueAdded> vas=valueAddedMapper.selectListByIds(ids); r.setValueAddedList(vas.stream().map(v->{AppProductSpuDetailRespVO.ValueAddedItem i=new AppProductSpuDetailRespVO.ValueAddedItem(); i.setId(v.getId()); i.setName(v.getName()); i.setPrice(v.getPrice()); i.setIsDefault(Objects.equals(spu.getDefaultSelectedValueAddedId(),v.getId())?1:0); return i;}).toList());} return r;}
public List<AppProductSkuRespVO> skuList(AppProductSkuListReqVO req){return saleableSkusBySpu(req.getSpuId()).stream().map(this::toSku).toList();}
public AppProductSkuRespVO skuDetail(AppProductSkuDetailReqVO req){MarketingProductSku sku=skuMapper.selectById(req.getSkuId()); if(sku==null||!isSkuSaleable(sku)) return null; MarketingProductSpu spu=spuMapper.selectById(sku.getMarketingSpuId()); if(spu==null||spu.getIsDeleted()) return null; return toSku(sku);} 
private AppProductSkuRespVO toSku(MarketingProductSku sku){AppProductSkuRespVO v=new AppProductSkuRespVO(); v.setSkuId(sku.getId()); v.setDailyRent(sku.getDailyRent()); v.setTotalRent(sku.getTotalRent()); v.setBuyoutAmount(sku.getBuyoutAmount()); v.setStock(sku.getStock()); v.setIsAllowOrder(sku.getIsAllowOrder()); v.setOfficialPrice(sku.getOfficialPrice()); v.setStrikethroughPrice(sku.getStrikethroughPrice()); List<AppProductSkuRespVO.PropertyValueItem> p=buildSkuProps(sku.getId()); v.setPropertyValues(p); v.setPicUrl(CollectionUtil.isEmpty(p)?null:splitFirst(skuPropertyValueMapper.selectListBySkuIds(List.of(sku.getId())).stream().map(MarketingProductSkuPropertyValue::getPicUrl).filter(StringUtils::isNotBlank).findFirst().orElse(null))); return v;}
private List<AppProductSkuRespVO.PropertyValueItem> buildSkuProps(Long skuId){List<MarketingProductSkuPropertyValue> links=skuPropertyValueMapper.selectListBySkuIds(List.of(skuId)); if(CollectionUtil.isEmpty(links)) return Collections.emptyList(); List<Long> spuValIds=links.stream().map(MarketingProductSkuPropertyValue::getMarketingSpuPropertyValueId).toList(); Map<Long,MarketingProductSpuPropertyValue> map=spuPropertyValueMapper.selectListByIds(spuValIds).stream().collect(Collectors.toMap(MarketingProductSpuPropertyValue::getId,e->e)); Set<Long> pids=map.values().stream().map(MarketingProductSpuPropertyValue::getProductPropertyId).collect(Collectors.toSet()); Set<Long> pvids=map.values().stream().map(MarketingProductSpuPropertyValue::getProductPropertyValueId).filter(Objects::nonNull).collect(Collectors.toSet()); Map<Long,String> pn=productPropertyMapper.selectListByIds(pids).stream().collect(Collectors.toMap(ProductProperty::getId,ProductProperty::getName)); Map<Long,String> pvn=productPropertyValueMapper.selectListByIds(pvids).stream().collect(Collectors.toMap(ProductPropertyValue::getId,ProductPropertyValue::getPropertyValue)); List<AppProductSkuRespVO.PropertyValueItem> out=new ArrayList<>(); for(MarketingProductSkuPropertyValue l:links){MarketingProductSpuPropertyValue sv=map.get(l.getMarketingSpuPropertyValueId()); if(sv==null)continue; AppProductSkuRespVO.PropertyValueItem i=new AppProductSkuRespVO.PropertyValueItem(); i.setPropertyId(sv.getProductPropertyId()); i.setPropertyName(pn.get(sv.getProductPropertyId())); i.setPropertyValue(sv.getProductPropertyValueId()==null?sv.getPropertyValue():pvn.get(sv.getProductPropertyValueId())); out.add(i);} return out;}
private List<MarketingProductSku> saleableSkusBySpu(Long spuId){return skuMapper.selectList(new LambdaQueryWrapper<MarketingProductSku>().eq(MarketingProductSku::getMarketingSpuId,spuId).eq(MarketingProductSku::getIsDeleted,false).eq(MarketingProductSku::getIsAllowOrder,1).gt(MarketingProductSku::getStock,0).orderByAsc(MarketingProductSku::getDailyRent));}
private boolean isSkuSaleable(MarketingProductSku sku){return !sku.getIsDeleted()&&Objects.equals(sku.getIsAllowOrder(),1)&&sku.getStock()!=null&&sku.getStock()>0;}
private LambdaQueryWrapper<MarketingProductSpu> baseSpu(){return new LambdaQueryWrapper<MarketingProductSpu>().eq(MarketingProductSpu::getIsDeleted,false).eq(MarketingProductSpu::getShelvesStatus,ShelvesStatusEnum.ON_SHELVES.getValue()).eq(MarketingProductSpu::getApprovalStatus, ApproveStatusEnum.APPROVE_PASS.getValue());}
private List<String> split(String s){return StringUtils.isBlank(s)?Collections.emptyList():Arrays.stream(s.split(",")).filter(StringUtils::isNotBlank).toList();}
private String splitFirst(String s){List<String> l=split(s); return CollectionUtil.isEmpty(l)?null:l.get(0);} }
