<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.bajiezu.cloud</groupId>
    <artifactId>bajiecloud-stone</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>
  <artifactId>bajiecloud-product</artifactId>
  <packaging>pom</packaging>

  <name>${project.artifactId}</name>
  <modules>
    <module>bajiecloud-product-api</module>
    <module>bajiecloud-product-server</module>
  </modules>
  <properties>
    <bajiecloud-common.version>1.0.0-SNAPSHOT</bajiecloud-common.version>
    <bajiecloud-scheduler.version>1.0.0-SNAPSHOT</bajiecloud-scheduler.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.bajiezu.cloud</groupId>
        <artifactId>bajiecloud-common</artifactId>
        <version>${bajiecloud-common.version}</version>
      </dependency>

      <dependency>
        <groupId>com.bajiezu.cloud</groupId>
        <artifactId>bajiecloud-product-api</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

</project>
