# 默认配置 - 所有环境通用设置
spring:
  application:
    name: system-server
  cloud:
    nacos:
      server-addr: ${mse.nacos.server-addr:nacos-test.example.com:8848}
      discovery:
        namespace: test
        group: DEFAULT_GROUP
        service: ${spring.application.name}
      config:
        namespace: test
        group: DEFAULT_GROUP
        file-extension: yaml
        import-check:
          enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: HikariPool
      auto-commit: true
      validation-timeout: 3000
  config:
    import: optional:mse

  main:
    allow-circular-references: true # 允许循环依赖，因为项目是三层架构，无法避免这个情况。
    allow-bean-definition-overriding: true # 允许 Bean 覆盖，例如说 Feign 等会存在重复定义的服务

  #redisson 的配置信息
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://${spring.data.redis.host}:${spring.data.redis.port}"
          password: ${spring.data.redis.password}
          username: ${spring.data.redis.username}
          database: ${spring.data.redis.database}


  # Servlet 配置
  servlet:
    # 文件上传相关配置项
    multipart:
      max-file-size: 16MB # 单个文件大小
      max-request-size: 32MB # 设置总上传的文件大小

  # Jackson 配置项
  jackson:
    serialization:
      write-dates-as-timestamps: true # 设置 LocalDateTime 的格式，使用时间戳
      write-date-timestamps-as-nanoseconds: false # 设置不使用 nanoseconds 的格式。例如说 1611460870.401，而是直接 1611460870401
      write-durations-as-timestamps: true # 设置 Duration 的格式，使用时间戳
      fail-on-empty-beans: false # 允许序列化无属性的 Bean

  # Cache 配置项
  cache:
    type: REDIS
    redis:
      time-to-live: 1h # 设置过期时间为 1 小时

server:
  port: 48081

# SpringDoc 配置
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  # 而是让两者共存，或者只使用一个
  swagger-ui:
    path: /swagger-ui.html
    enabled: true  # 改为 true，两者可以共存
    display-request-duration: true
    operations-sorter: method
    tags-sorter: alpha
  # 配置默认分组
  group-configs:
    - group: default
      paths-to-match: /**

# MyBatis Plus 的配置项
mybatis-plus:
  mapper-locations:
    - classpath*:mapper/*.xml
    - classpath*:mapper/**/*.xml
    # 实体扫描
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
    # 在控制台打印SQL日志，便于调试
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: NONE # “智能”模式，基于 IdTypeEnvironmentPostProcessor + 数据源的类型，自动适配成 AUTO、INPUT 模式。
      #      id-type: AUTO # 自增 ID，适合 MySQL 等直接自增的数据库
      #      id-type: INPUT # 用户输入 ID，适合 Oracle、PostgreSQL、Kingbase、DB2、H2 数据库
      #      id-type: ASSIGN_ID # 分配 ID，默认使用雪花算法。注意，Oracle、PostgreSQL、Kingbase、DB2、H2 数据库时，需要去除实体类上的 @KeySequence 注解
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    banner: false # 关闭控制台的 Banner 打印
  type-aliases-package: com.bajiezu.**.entity

mybatis-plus-join:
  banner: false # 关闭控制台的 Banner 打印

# VO 转换（数据翻译）相关
easy-trans:
  #启用redis缓存 如果不用redis请设置为false
  is-enable-redis: false
  #启用全局翻译(拦截所有responseBody进行自动翻译)，如果对于性能要求很高可关闭此配置在方法上使用注解翻译
  is-enable-global: true
  #启用平铺模式 手动翻译无效
  is-enable-tile: true
  #字典缓存放到redis 微服务模式请开启
  dict-use-redis: true
  #使用@RpcTrans来标记哪些类可以进行RPC翻译，默认为关闭，多团队协作推荐开启
  is-enable-custom-rpc: true
  # ruoyi相关的框架请开启
  is-enable-map-result: true
  # 反向翻译数据库类型 mysql
  db-type: mysql
  # Mybatis-plus 为 3.5.3.2版本以上的3.x 版本请设置为true
  mp-new: true

--- #################### RPC 远程调用相关配置 ####################

--- #################### 消息队列相关 ####################

# rocketmq 配置项，对应 RocketMQProperties 配置类
rocketmq:
  # Producer 配置项
  producer:
    group: ${spring.application.name}_PRODUCER # 生产者分组



--- #################### 定时任务相关配置 ####################

xxl:
  job:
    executor:
      appname: ${spring.application.name} # 执行器 AppName
      logpath: ${user.home}/logs/xxl-job/${spring.application.name} # 执行器运行日志文件存储磁盘路径
    accessToken: default_token # 执行器通讯TOKEN


--- #################### 芋道相关配置 ####################

bajie:
  info:
    version: 1.0.0
    base-package: com.bajiezu.cloud.system
  web:
    admin-ui:
      url: http://dashboard.bajie.bajie.cn # Admin 管理后台 UI 的地址
  xss:
    enable: false
    exclude-urls: # 如下 url，仅仅是为了演示，去掉配置也没关系
      - ${management.endpoints.web.base-path}/** # 不处理 Actuator 的请求
  api-encrypt:
    enable: true # 是否开启 API 加密
    algorithm: AES # 加密算法，支持 AES、RSA 等
    request-key: 52549111389893486934626385991395 # 【AES 案例】请求加密的秘钥，，必须 16、24、32 位
    response-key: 96103715984234343991809655248883 # 【AES 案例】响应加密的秘钥，AES 案例，必须 16、24、32 位




